name: mockify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.0
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/
  
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Variable.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-VariableItalic.ttf





