// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3WNYSPqwN7x2zlQsbcQ1xrMriWajP4qY',
    appId: '1:812939948258:web:da2a149f9b6ba01a28eebb',
    messagingSenderId: '812939948258',
    projectId: 'mockify0101',
    authDomain: 'mockify0101.firebaseapp.com',
    storageBucket: 'mockify0101.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcLv-MhYdMIIfZPeUnC5tza8lpC2eJd4M',
    appId: '1:812939948258:android:338f582d83dbbc6c28eebb',
    messagingSenderId: '812939948258',
    projectId: 'mockify0101',
    storageBucket: 'mockify0101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqkzdwy9gzRx83qoO-I83iQDNGFaU5IS4',
    appId: '1:812939948258:ios:99718274c076ab5128eebb',
    messagingSenderId: '812939948258',
    projectId: 'mockify0101',
    storageBucket: 'mockify0101.firebasestorage.app',
    iosBundleId: 'com.example.mockify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqkzdwy9gzRx83qoO-I83iQDNGFaU5IS4',
    appId: '1:812939948258:ios:99718274c076ab5128eebb',
    messagingSenderId: '812939948258',
    projectId: 'mockify0101',
    storageBucket: 'mockify0101.firebasestorage.app',
    iosBundleId: 'com.example.mockify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3WNYSPqwN7x2zlQsbcQ1xrMriWajP4qY',
    appId: '1:812939948258:web:d5f7799febabcd0c28eebb',
    messagingSenderId: '812939948258',
    projectId: 'mockify0101',
    authDomain: 'mockify0101.firebaseapp.com',
    storageBucket: 'mockify0101.firebasestorage.app',
  );
}
